### ISSUE TITLE
TypeError: type() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by jiangerxiaozhao** [vadimkantorov/caffemodel2pytorch#1]
python=2.7

File "../oicr-master/caffemodel2pytorch.py", line 354, in init_weight_bias
    self.weight = nn.Parameter(weight.type_as(self.weight), requires_grad = self.weight.requires_grad)
  File "../lib/python2.7/site-packages/torch/tensor.py", line 41, in type_as
    return self.type(tensor.type())
TypeError: type() takes exactly 2 arguments (1 given)

What advice do you have?

In addition, what version of python and pytorch are you using?

**Comment by vadimkantorov** [comment]
I think it was also python 2.7 and some early alpha of pytorch 0.4: things may have changed since.

(Sorry, it's a long time I'm not working with this code, you'll need to debug and fix it yourself, but I'll take in any fixes!)

**Comment by jiangerxiaozhao** [comment]
@vadimkantorov Thank you very much, pytorch 0.4 worked.
