### ISSUE TITLE
How to use converted-model (pt)??

### ISSUE THREAD

**Issue by edwardcho** [vadimkantorov/caffemodel2pytorch#10]
Hello.
My caffemodel was changed pt-model (pytorch model) using your convertor.
But, I do not know how to use it.

I think that inference or training of pytorch should need two files.
1. definition python code.
2. pt model

If you can, please upload sample code (inference code and training)

**Comment by vadimkantorov** [comment]
You are right. You would need Python code as well.

Unfortunately, I don't work on this codebase anymore, so can't provide any additional examples. The example with OICR conversion in README should be sufficient. You get a nn.Module model object, and then train/infer in PyTroch as usual.

Good luck!
