### ISSUE TITLE
google.protobuf.text_format.ParseError: 52:3 : Message type "caffe.LayerParameter" has no field named "bn_param".

### ISSUE THREAD

**Issue by Soldelli** [vadimkantorov/caffemodel2pytorch#15]
Dear @vadimkantorov , when running your code I encounter the error:

google.protobuf.text_format.ParseError: 52:3 : Message type "caffe.LayerParameter" has no field named "bn_param".

It is raised in [line](https://github.com/vadimkantorov/caffemodel2pytorch/blob/master/caffemodel2pytorch.py#L72) of your script `caffemodel2pytorch.py`

I initialize the model as: 
```
kwargs = {'caffe_proto' : 'https://raw.githubusercontent.com/BVLC/caffe/master/src/caffe/proto/caffe.proto',
         'phase'    : caffe.TEST, 
         'weights'  : './models/resnet200_anet_2016.caffemodel'
            }
prototxt='./models/resnet200_anet_2016_deploy.prototxt'

model = caffe.Net(prototxt, **kwargs)
```

You can download the `prototxt` and `caffemodel` files with the commands:
```
wget -O models/resnet200_anet_2016.caffemodel https://yjxiong.blob.core.windows.net/anet-2016/resnet200_anet_2016.caffemodel
wget -O models/resnet200_anet_2016_deploy.prototxt https://yjxiong.blob.core.windows.net/anet-2016/resnet200_anet_2016_deploy.prototxt
```

Could you please help me out with this issue?

Best,
Mattia

**Comment by Soldelli** [comment]
If anyone end up having such an issue, it is related to a different distribution of Caffe with respect to the default one. Therefore the correct `caffe.proto` file must be referenced.

For example in my case, the correct one is: 
```
'caffe_proto' : 'https://raw.githubusercontent.com/yjxiong/caffe/b301fa0b3f9c24037684eca5293bb3a304a285dd/src/caffe/proto/caffe.proto'
```

A small note, if you locate the protofile in a github repo (eg. [caffe.proto)](https://github.com/yjxiong/caffe/blob/b301fa0b3f9c24037684eca5293bb3a304a285dd/src/caffe/proto/caffe.proto):
- Tap on the `raw` icon on the upper-right part of the page (see image)
- Copy the URL of the raw page and use it to set `caffe_proto`.

![example](https://user-images.githubusercontent.com/26504816/84574810-b83c5600-adb1-11ea-99a0-61db0ff412f3.jpg)

**Comment by vadimkantorov** [comment]
Good luck with your project @Soldelli. Thanks for contributing instructions for others.

**Comment by anilbatra2185** [comment]
thanks @vadimkantorov  for sharing the code.

Hi @Soldelli, Thanks for sharing the solution, however, I am facing an additional error of `module name can\'t contain "."`. I am wondering which version of pytorch you are using for the inference. I am also wondering, how did you loaded the BatchNorm caffe weights.

Thanks in advance!
Anil
