### ISSUE TITLE
caffe to pytorch model

### ISSUE THREAD

**Issue by arnabsharma91** [vadimkantorov/caffemodel2pytorch#16]
Hi!
I am trying to use your tool to convert a caffe model to a pytorch model. Basically I have [this](https://drive.google.com/file/d/1FW1I47rhCRCz8BTc9ZmRFxghXQ33VtFn/view) .protxt file and [this](https://drive.google.com/file/d/1fKkxEx2WIKUfeJan30o-U76QvEU4aY84/view) as a caffemodel. Would it be possible to use your tool and directly get a pytorch model which can be immediately used for prediction like its equivalent caffe model?

Thanks,
Arnab

**Comment by vadimkantorov** [comment]
Here's a list of supported modules: https://github.com/vadimkantorov/caffemodel2pytorch/blob/master/caffemodel2pytorch.py#L287-L296

If your model uses only them, you may be lucky and it may work out of the box.

Otherwise, you may need to add support for needed modules yourself.

**Comment by arnabsharma91** [comment]
Thanks a lot!
