### ISSUE TITLE
When prototxt does not have operation in eltwise layer, it raises error

### ISSUE THREAD

**Issue by eebeer** [vadimkantorov/caffemodel2pytorch#2]
When prototxt does not have operation in eltwise layer, it raises error (ex: https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-50-deploy.prototxt). 

In caffe.proto, default operation is set as SUM.

```
    caffe_proto = 'https://raw.githubusercontent.com/BVLC/caffe/master/src/caffe/proto/caffe.proto'
  File "./caffemodel2pytorch/caffemodel2pytorch.py", line 83, in __init__    module = module_constructor(param)
  File "./caffemodel2pytorch/caffemodel2pytorch.py", line 291, in <lambda>
    Eltwise = lambda param: [torch.mul, torch.add, torch.max][param['operation']]
KeyError: 'operation'
```

**Comment by vadimkantorov** [comment]
Does it work if you replace this by `Eltwise = lambda param: [torch.mul, torch.add, torch.max][param.get('operation', 1)]`?

**Comment by vadimkantorov** [comment]
I put this in!

**Comment by vadimkantorov** [comment]
Also please mind that I do not support BatchNorm layer. But feel free to send a PR if you implement some support.
