### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by olowu289** [vadimkantorov/caffemodel2pytorch#27]
Im working on the project, micro-structural reconstruction using machine learning and im using the MCRpy and I'm having this attribute error. 
 

import mcrpy as mcr
import numpy as np
from PIL import Image

# Load the image using Pillow
image = Image.open('/content/drive/MyDrive/AlubronzeCuAl20v500.png')
# Convert the image to a NumPy array
slice_2d = np.array(image)

# Define the size of the 3D volume element
size_3d = (100, 100, 100)

# Define the descriptors to use
descriptors = [mcr.Descriptor.TwoPointCorrelationFFT()]

# Reconstruct the 3D volume element
volume_3d = mcr.reconstruct(slice_2d, size_3d, descriptors)

the error 
AttributeError: module 'mcrpy' has no attribute 'Descriptor'

**Comment by vadimkantorov** [comment]
mcr/mcrpy seems fully unrelated to this repo. Please open an issue instead in mcr repos!
