### ISSUE TITLE
exception had an invalid syntax

### ISSUE THREAD

**Issue by alanhzh** [vadimkantorov/caffemodel2pytorch#5]
File "caffemodel2pytorch.py", line 134
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by alanhzh** [comment]
Problem solved, it looks like Okey to switch to except:

**Comment by vadimkantorov** [comment]
It now reads as "Exception as e", so the problem should be fixed now. Please let me know if it works. Thanks!
